package com.tanglesites

import com.tanglesites.ManifestPropertyService.*

val ListOfValues = List(
  "en",
  "fr",
  "es",
  "es-mx",
  "de",
  "it",
  "ja",
  "pt-br",
  "ru",
  "pl",
  "ko",
  "zh-cht",
  "zh-chs"
)
val ListOfTableNames = List(
  "DestinyArtDyeChannelDefinition",
  "DestinyArtDyeReferenceDefinition",
  "DestinyPlaceDefinition",
  "DestinyActivityDefinition",
  "DestinyActivityTypeDefinition",
  "DestinyClassDefinition",
  "DestinyGenderDefinition",
  "DestinyInventoryBucketDefinition",
  "DestinyRaceDefinition",
  "DestinyUnlockDefinition",
  "DestinyStatGroupDefinition",
  "DestinyProgressionMappingDefinition",
  "DestinyFactionDefinition",
  "DestinyVendorGroupDefinition",
  "DestinyRewardSourceDefinition",
  "DestinyUnlockValueDefinition",
  "DestinyRewardMappingDefinition",
  "DestinyRewardSheetDefinition",
  "DestinyItemCategoryDefinition",
  "DestinyDamageTypeDefinition",
  "DestinyActivityModeDefinition",
  "DestinyMedalTierDefinition",
  "DestinyAchievementDefinition",
  "DestinyActivityGraphDefinition",
  "DestinyActivityInteractableDefinition",
  "DestinyBondDefinition",
  "DestinyCharacterCustomizationCategoryDefinition",
  "DestinyCharacterCustomizationOptionDefinition",
  "DestinyCollectibleDefinition",
  "DestinyDestinationDefinition",
  "DestinyEntitlementOfferDefinition",
  "DestinyEquipmentSlotDefinition",
  "DestinyEventCardDefinition",
  "DestinyFireteamFinderActivityGraphDefinition",
  "DestinyFireteamFinderActivitySetDefinition",
  "DestinyFireteamFinderLabelDefinition",
  "DestinyFireteamFinderLabelGroupDefinition",
  "DestinyFireteamFinderOptionDefinition",
  "DestinyFireteamFinderOptionGroupDefinition",
  "DestinyStatDefinition",
  "DestinyInventoryItemDefinition",
  "DestinyInventoryItemLiteDefinition",
  "DestinyItemTierTypeDefinition",
  "DestinyLoadoutColorDefinition",
  "DestinyLoadoutIconDefinition",
  "DestinyLoadoutNameDefinition",
  "DestinyLocationDefinition",
  "DestinyLoreDefinition",
  "DestinyMaterialRequirementSetDefinition",
  "DestinyMetricDefinition",
  "DestinyObjectiveDefinition",
  "DestinySandboxPerkDefinition",
  "DestinyPlatformBucketMappingDefinition",
  "DestinyPlugSetDefinition",
  "DestinyPowerCapDefinition",
  "DestinyPresentationNodeDefinition",
  "DestinyProgressionDefinition",
  "DestinyProgressionLevelRequirementDefinition",
  "DestinyRecordDefinition",
  "DestinyRewardAdjusterPointerDefinition",
  "DestinyRewardAdjusterProgressionMapDefinition",
  "DestinyRewardItemListDefinition",
  "DestinySackRewardItemListDefinition",
  "DestinySandboxPatternDefinition",
  "DestinySeasonDefinition",
  "DestinySeasonPassDefinition",
  "DestinySocialCommendationDefinition",
  "DestinySocketCategoryDefinition",
  "DestinySocketTypeDefinition",
  "DestinyTraitDefinition",
  "DestinyUnlockCountMappingDefinition",
  "DestinyUnlockEventDefinition",
  "DestinyUnlockExpressionMappingDefinition",
  "DestinyVendorDefinition",
  "DestinyMilestoneDefinition",
  "DestinyActivityModifierDefinition",
  "DestinyReportReasonCategoryDefinition",
  "DestinyArtifactDefinition",
  "DestinyBreakerTypeDefinition",
  "DestinyChecklistDefinition",
  "DestinyEnergyTypeDefinition",
  "DestinySocialCommendationNodeDefinition",
  "DestinyGuardianRankDefinition",
  "DestinyGuardianRankConstantsDefinition",
  "DestinyLoadoutConstantsDefinition",
  "DestinyFireteamFinderConstantsDefinition",
  "DestinyGlobalConstantsDefinition"
)

@main def main(): Unit =
  println("Hello world!")
  val pairs = for {
    lang <- ListOfValues
    table <- ListOfTableNames
  } yield List(lang, table)

  pairs.foreach(x => JsonWorldComponentContentTables(x.last, x.head))
  // pairs.foreach(x => print(x))
